{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cellranger
  version: {{ version|replace("-", "_") }}

source:
  fn: cellranger_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/cellranger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cellranger/cellranger_{{ version }}.tar.gz
  sha256: 5d38f288c752bbb9cea6ff830b8388bdd65a8571fd82d8d96064586bd588cf99

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rematch
    - r-tibble
  run:
    - r-base
    - r-rematch
    - r-tibble

test:
  commands:
    - $R -e "library('cellranger')"           # [not win]
    - "\"%R%\" -e \"library('cellranger')\""  # [win]

about:
  home: https://github.com/rsheets/cellranger
  license: MIT
  summary: Helper functions to work with spreadsheets and the "A1:D10" style of cell range specification.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
