travis:
  secure:
    BINSTAR_TOKEN: IsHu8uuSJ8VtR1aCwpUrE5LxlXg3s9XmJ3cOTWoTWQpNqlF+LmSMEgIOX5vYNei0joJ9Hr1z4hAwQIwh/sBNM2ZfrtR3PS8yLVXCN158GgNzeMbC/tDp7fb1MsTVQRq12Pz9ug73cRidf5D+qzwS9R35KcH8Kb9NUq4qbKBEBbJOY93DTNW822gFiFvpYHBdWgXAPabn1f1u11HCEPbraEQbSStL5g9sP59fEKxIZIrmg1zuLmkN8zdk8sDPK41Z0q7PY9dKBRGXu+CupH9ww8pV7mm+iCI5S9kOJAqfTGt8On0JRfRIKsFIN3lNPIh3kD72fBm3YXRitQpYcpg+pRVjGSwkTEDG8INKZBwznFRln4rbxBee7EMFpdpFZgcqVApdb9yrLODJqEx+HHwcFzrtAlC22VrulJql+sXvqeYRuIEtEzB/CYDVaKxZ7aSRmv1IyoIb22b0q42mWJYOQR6+L/VjFWDMyorOzmydRIZhHT2AJUUOA+QW9EythOJtycoYCRbsVKah67o9m9pbQ8w0GNTTXAZwd37TVQN3XLg3lDdLyQsrIczKDOfBD4l0SLV3RTesGG8hEK/SEpZLS3TPMLmRamRiJ1EcF+RjCDcOE8oNE7otk116KAp6e74H3tY7H4Bp6gYU87wXw7CqvMXSworINfaBeFpLMdAC0b8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
