travis:
  secure:
    BINSTAR_TOKEN: mfuWVMyZW7VYhd0THSpoRp+SGLfll5AMJwlLs28JoTCGLCzSJjOypYzaEegVV7CWbd5++g4y0ZX9jWjWsZojPelSSDRJ5lJ+Gurw82bw8FBIijGX0q18pb7q2ptWQy0d28aZNbdgdRL7yzbFYPBJ0mrX8+maIm1lot59Go5ZGAmjsaQuKTcEESl37AuBJG3MOU9C2UfkFbei1wh7FUvr7iHAihA+og3URtVtl3C7SxSYkyZZz/ubJGnoTu8sPdZ7S3H4NTzgxbNXd9PAIx33/ZY6a75jiD1iF0/8xTqF5UCXqXJa72ZqF0ha3uc0CZuRQLTpbriuvSs7q72AR77YHGNukKFr4keumrM+BRp+UJivwyJcj89jO9mvKEvOkN8dMvHR4WpuxYllAcvv6/V59qN1QPRF4XZOytUab2CtZHSkxLOnOaFU0fY8AV8X8oI5UweVMnz1YgzMgPt8hkALn7rKA/WVnVSsVyGGB4steuM8jl8ekrZq5AxjwAhiHqX7mRoal1TU96uAsEJQwIvq76Kw82QQnRxhxpmynHgJ3Y5E/0wuVprMvT3QGErBzhFofIU9lpuEnpd9yXZzjIGkWowD6yxF56TptnAGnyNG107i+hyO45nvK69Af76mZz7bfXcQC9caCQ3bjD/faYaON/4SzssWdhS1apN6gtUFqrY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
